{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/{{ required "A valid .Values.rbac.apiVersion entry required!" .Values.rbac.apiVersion }}
kind: Role
metadata:
  name: {{ include "app.fullname" $ }}
  namespace: {{ $.Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "app.chart" $ }}
    app.kubernetes.io/name: {{ include "app.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
rules:
{{ toYaml .Values.dashboard.role.rules }}
{{- end }}
