dependencies:
  - name: microservice
    version: 0.1.0
    repository: "file://../microservice"
    alias: auth
    condition: auth.enabled
  - name: microservice
    version: 0.1.0
    repository: "file://../microservice"
    alias: user
    condition: user.enabled
  - name: microservice
    version: 0.1.0
    repository: "file://../microservice"
    alias: pubsub
    condition: pubsub.enabled
# AWS localstack (for local development)
  - name: microservice
    version: 0.1.0
    repository: "file://../microservice"
    alias: localstack
    condition: localstack.enabled
# External charts: https://github.com/helm/charts/blob/master/stable
  - name: kubernetes-dashboard
    version: 1.5.2
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: kubernetes-dashboard.enabled
  - name: heapster
    version: 0.3.3
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: heapster.enabled
  - name: cert-manager
    namespace: cert-manager
    version: v0.8.1
    repository: https://charts.jetstack.io # `helm repo add jetstack https://charts.jetstack.io`
  - name: nginx-ingress
    version: 1.6.18
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: nginx-ingress.enabled
  - name: mysql
    version: 1.2.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: mysql.enabled
  - name: phpmyadmin
    version: 2.2.5
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: phpmyadmin.enabled
