ingress:
  issuerName: selfsigned #letsencrypt
  issuerKind: Issuer
  class: nginx
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/dashboard)$ $1/ permanent;
  hosts:
    - host: go-api-boilerplate.local
      paths:
        - path: /dashboard(/|$)(.*)
          backend:
            serviceName: kubernetes-dashboard
            servicePort: 443
        # - path: /localstack(/|$)(.*)
        #   backend:
        #     serviceName: go-api-boilerplate-localstack
        #     servicePort: 4567
        - path: /phpmyadmin(/|$)(.*)
          backend:
            serviceName: go-api-boilerplate-phpmyadmin
            servicePort: 443
        - path: /auth(/|$)(.*)
          backend:
            serviceName: go-api-boilerplate-auth
            servicePort: 3000
        - path: /users(/|$)(.*)
          backend:
            serviceName: go-api-boilerplate-user
            servicePort: 3000
  tls:
    - secretName: go-api-boilerplate-tls
      hosts:
        - go-api-boilerplate.local

kubernetes-dashboard:
  enableInsecureLogin: true
  fullnameOverride: 'kubernetes-dashboard'
  extraArgs:
    - '--heapster-host=http://heapster.default:8082'

heapster:
  fullnameOverride: 'heapster'

cert-manager:
  ingressShim:
    defaultIssuerName: selfsigned #letsencrypt
    defaultIssuerKind: Issuer
  # Override the namespace used to store DNS provider credentials etc. for ClusterIssuer
  # resources. By default, the same namespace as cert-manager is deployed within is
  # used. This namespace will not be automatically created by the Helm chart.
  clusterResourceNamespace: go-api-boilerplate
  extraArgs:
    # Use this flag to set a namespace that cert-manager will use to store
    # supporting resources required for each ClusterIssuer (default is kube-system)
    - --cluster-resource-namespace=go-api-boilerplate

issuer:
  name: selfsigned
  kind: Issuer
  selfSigned: true
  # name: letsencrypt
  # kind: Issuer
  # server: https://acme-v02.api.letsencrypt.org/directory
  # email: example@example.com
  # secretName: go-api-boilerplate-tls
  # http01: true

phpmyadmin:
  service:
    port: 443
  db:
    port: 3306
    host: go-api-boilerplate-mysql

mysql:
  existingSecret: mysql-secret
  mysqlUser: goapiboilerplate
  initializationFiles:
    privileges.sql: |-
      GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
      GRANT ALL PRIVILEGES ON *.* TO 'user'@'%' WITH GRANT OPTION;
      FLUSH PRIVILEGES;
    base_schema.sql: |-
      CREATE DATABASE IF NOT EXISTS goapiboilerplate DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

# AWS localstack https://github.com/localstack/localstack
localstack:
  enabled: false
#   nameOverride: localstack
#   image:
#     repository: localstack/localstack
#     tag: 0.8.10
#     pullPolicy: IfNotPresent
#   service:
#     ports:
#       - name: dynamodb
#         internalPort: 4569
#         externalPort: 4569
#       - name: ui
#         internalPort: 4567
#         externalPort: 4567
#   env:
#     - name: SERVICES
#       value: "dynamodb:4569"
#     - name: PORT_WEB_UI
#       value: "4567"

pubsub:
  nameOverride: pubsub
  serviceAccountName: goapiboilerplate
  image:
    repository: vardius/pubsub
    tag: 1.0.6
    pullPolicy: IfNotPresent
  service:
    ports:
      - name: grpc
        internalPort: 3001
        externalPort: 3001
  envFromConfigMapRefs:
    - pubsub-config
  readiness:
    initialDelaySeconds: 20
    timeoutSeconds: 5
    exec:
      command: ["/bin/grpc_health_probe", "-addr=:3001"]
  liveness:
    initialDelaySeconds: 20
    exec:
      command: ["/bin/grpc_health_probe", "-addr=:3001"]

auth:
  nameOverride: auth
  serviceAccountName: goapiboilerplate
  image:
    repository: auth
    tag: local
    pullPolicy: Never
  service:
    ports:
      - name: http
        internalPort: 3000
        externalPort: 3000
      - name: grpc
        internalPort: 3001
        externalPort: 3001
  initContainers:
    - name: migrations
      image:
        repository: migrate
        tag: local
        pullPolicy: IfNotPresent
      command:
        - '/migrate'
      args:
        - '-source'
        - 'file:///migrations'
        - '-database'
        - 'mysql://root:password@tcp(go-api-boilerplate-mysql:3306)/goapiboilerplate?multiStatements=true' # @TODO: think of a better way of passing user:password data
        - 'up'
  envFromSecretRefs:
    - app-secret
    - user-secret
  envFromConfigMapRefs:
    - app-config
    - http-config
    - grpc-config
    - mysql-config
    - auth-config
    # - aws-config
  env:
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          key: mysql-root-password
          name: mysql-secret
  readiness:
    initialDelaySeconds: 20
    timeoutSeconds: 5
    httpGet:
      path: /v1/readiness
      port: 3000
  liveness:
    initialDelaySeconds: 20
    httpGet:
      path: /v1/health
      port: 3000

user:
  nameOverride: user
  serviceAccountName: goapiboilerplate
  image:
    repository: user
    tag: local
    pullPolicy: Never
  service:
    ports:
      - name: http
        internalPort: 3000
        externalPort: 3000
      - name: grpc
        internalPort: 3001
        externalPort: 3001
  initContainers:
    - name: migrations
      image:
        repository: migrate
        tag: local
        pullPolicy: IfNotPresent
      command:
        - '/migrate'
      args:
        - '-source'
        - 'file:///migrations'
        - '-database'
        - 'mysql://root:password@tcp(go-api-boilerplate-mysql:3306)/goapiboilerplate?multiStatements=true' # @TODO: think of a better way of passing user:password data
        - 'up'
  envFromSecretRefs:
    - app-secret
    - user-secret
  envFromConfigMapRefs:
    - app-config
    - http-config
    - grpc-config
    - mysql-config
    - user-config
    # - aws-config
  env:
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          key: mysql-root-password
          name: mysql-secret
  readiness:
    initialDelaySeconds: 20
    timeoutSeconds: 5
    httpGet:
      path: /v1/readiness
      port: 3000
  liveness:
    initialDelaySeconds: 20
    httpGet:
      path: /v1/health
      port: 3000

secrets:
  - name: app-secret
    type: Opaque
    data:
      APP_SECRET: Y2hhbmdlbWU= # changeme
  - name: mysql-secret
    type: Opaque
    data:
      mysql-password: cGFzc3dvcmQ= # password
      mysql-root-password: cGFzc3dvcmQ= # password
  - name: user-secret
    type: Opaque
    data:
      USER_CLIENT_ID: MDc5ODE3M2UtNjE0Yy00Zjc4LTk5NmItZTllNjNlMDFlZDIw # 0798173e-614c-4f78-996b-e9e63e01ed20
      USER_CLIENT_SECRET: MDc5ODE3M2UtNjE0Yy00Zjc4LTk5NmItZTllNjNlMDFlZDIw # 0798173e-614c-4f78-996b-e9e63e01ed20

configMaps:
  - name: app-config
    data:
      APP_ENV: development
      APP_SHUTDOWN_TIMEOUT: '5s'
  - name: http-config
    data:
      HTTP_PORT: '3000'
      HTTP_ORIGINS: go-api-boilerplate.local|localhost|0.0.0.0|127.0.0.1
  - name: grpc-config
    data:
      GRPC_PORT: '3001'
  - name: mysql-config
    data:
      MYSQL_HOST: 'go-api-boilerplate-mysql'
      MYSQL_PORT: '3306'
      MYSQL_NAME: 'goapiboilerplate'
      MYSQL_USER: 'root'
  - name: pubsub-config
    data:
      HOST: '0.0.0.0'
      PORT: '3001'
      QUEUE_BUFFER_SIZE: '100'
      KEEPALIVE_MIN_TIME: '5m' # if a client pings more than once every 5 minutes (default), terminate the connection
      KEEPALIVE_TIME: '2h'     # ping the client if it is idle for 2 hours (default) to ensure the connection is still active
      KEEPALIVE_TIMEOUT: '20s' # wait 20 second (default) for the ping ack before assuming the connection is dead
      LOG_VERBOSE_LEVEL: '3'
  - name: auth-config
    data:
      HOST: '0.0.0.0'
      COMMAND_BUS_BUFFER: '100'
      PUBSUB_HOST: 'go-api-boilerplate-pubsub'
      PUBSUB_PORT: '3001'
      USER_HOST: 'go-api-boilerplate-user'
      GRPC_SERVER_MIN_TIME: '5m'    # if a client pings more than once every 5 minutes (default), terminate the connection
      GRPC_SERVER_TIME: '2h'        # ping the client if it is idle for 2 hours (default) to ensure the connection is still active
      GRPC_SERVER_TIMEOUT: '20s'    # wait 20 second (default) for the ping ack before assuming the connection is dead
      GRPC_CLIENT_TIME: '10s'       # send pings every 10 seconds if there is no activity
      GRPC_CLIENT_TIMEOUT: '20s'    # wait 20 second for ping ack before considering the connection dead
      MYSQL_CONN_MAX_LIFETIME: '5m' #  sets the maximum amount of time a connection may be reused
      MYSQL_MAX_IDLE_CONNS: '0'     # sets the maximum number of connections in the idle
      MYSQL_MAX_OPEN_CONNS: '5'     # sets the maximum number of connections in the idle
  - name: user-config
    data:
      HOST: '0.0.0.0'
      COMMAND_BUS_BUFFER: '100'
      PUBSUB_HOST: 'go-api-boilerplate-pubsub'
      PUBSUB_PORT: '3001'
      AUTH_HOST: 'go-api-boilerplate-auth'
      GRPC_SERVER_MIN_TIME: '5m'    # if a client pings more than once every 5 minutes (default), terminate the connection
      GRPC_SERVER_TIME: '2h'        # ping the client if it is idle for 2 hours (default) to ensure the connection is still active
      GRPC_SERVER_TIMEOUT: '20s'    # wait 20 second (default) for the ping ack before assuming the connection is dead
      GRPC_CLIENT_TIME: '10s'       # send pings every 10 seconds if there is no activity
      GRPC_CLIENT_TIMEOUT: '20s'    # wait 20 second for ping ack before considering the connection dead
      MYSQL_CONN_MAX_LIFETIME: '5m' #  sets the maximum amount of time a connection may be reused
      MYSQL_MAX_IDLE_CONNS: '0'     # sets the maximum number of connections in the idle
      MYSQL_MAX_OPEN_CONNS: '5'     # sets the maximum number of connections in the idle
  # - name: aws-config
  #   data:
      # AWS_REGION: 'us-east-1'
      # AWS_ENDPOINT: 'http://go-api-boilerplate-localstack:4569'
